# Generated by Django 4.2.23 on 2025-07-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_actor_movie_actress_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actress',
            old_name='Actress_name',
            new_name='actress_name',
        ),
        migrations.AlterField(
            model_name='actor',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.movie'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.movie'),
        ),
    ]
