# Generated by Django 4.2.23 on 2025-07-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_rename_actress_name_actress_actress_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='voteup',
            field=models.IntegerField(default=0),
        ),
    ]
