# Generated by Django 4.2.23 on 2025-07-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_movie_voteup'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_image',
            field=models.ImageField(blank=True, null=True, upload_to='actor/'),
        ),
        migrations.AddField(
            model_name='actress',
            name='actor_image',
            field=models.ImageField(blank=True, null=True, upload_to='Actress/'),
        ),
    ]
