# Generated by Django 4.2.23 on 2025-07-30 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_actor_actor_image_actress_actor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actress',
            old_name='actor_image',
            new_name='actress_image',
        ),
    ]
