# Generated by Django 4.2.23 on 2025-07-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0008_rename_actor_image_actress_actress_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='actress_image',
            field=models.ImageField(blank=True, null=True, upload_to='actress/'),
        ),
    ]
