# Generated by Django 4.2.23 on 2025-07-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0009_movie_movie_image_alter_actress_actress_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
