# Generated by Django 4.2.23 on 2025-07-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0010_movie_movie_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
